apiVersion: v1
kind: Secret
metadata:
  name: {{ include "central-scan-listener.secretName" . }}
type: Opaque
stringData:
  appId: "{{ .Values.githubApp.appId }}"
  privateKey: |
    {{ .Values.githubApp.privateKey | indent 4 }}
  webhookSecret: "{{ .Values.githubApp.webhookSecret }}"
