apiVersion: v1
kind: Service
metadata:
  name: scan-dispatcher
  labels:
    app: scan-dispatcher
spec:
  type: ClusterIP
  selector:
    app: scan-dispatcher
  ports:
    - name: http
      port: 80
      targetPort: 3000
